"""Add subject to ExamRequest and remove status

Revision ID: 258829d23348
Revises: 4204d0b9b7ad
Create Date: 2024-11-05 16:57:33.578562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258829d23348'
down_revision: Union[str, None] = '4204d0b9b7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_requests', sa.Column('subject', sa.String(), nullable=True))
    op.drop_column('exam_requests', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_requests', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exam_requests', 'subject')
    # ### end Alembic commands ###
