"""Updated models with relationships and foreign keys

Revision ID: 4204d0b9b7ad
Revises: 4e561beebc1a
Create Date: 2024-10-28 19:16:23.244966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4204d0b9b7ad'
down_revision: Union[str, None] = '4e561beebc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_requests', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam_requests', 'exams', ['exam_id'], ['id'])
    op.drop_column('exam_requests', 'subject')
    op.add_column('professors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professors', 'users', ['user_id'], ['id'])
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'user_id')
    op.drop_constraint(None, 'professors', type_='foreignkey')
    op.drop_column('professors', 'user_id')
    op.add_column('exam_requests', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exam_requests', type_='foreignkey')
    op.drop_column('exam_requests', 'exam_id')
    # ### end Alembic commands ###
