"""Add relationship exams to Professor

Revision ID: 59b014db565d
Revises: a6f1d118f493
Create Date: 2025-01-08 18:51:58.628505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b014db565d'
down_revision: Union[str, None] = 'a6f1d118f493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exams', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'student_id')
    # ### end Alembic commands ###
