"""Add phone_number to professors

Revision ID: 681641d9c945
Revises: 6f597b28cf4e
Create Date: 2024-11-26 12:27:09.399063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681641d9c945'
down_revision: Union[str, None] = '6f597b28cf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('professors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_professors_email', table_name='professors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_professors_email', 'professors', ['email'], unique=True)
    op.alter_column('professors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
