"""Add classroom_id to exam_requests

Revision ID: 6c860184a399
Revises: 3312a30ce7d9
Create Date: 2024-11-26 18:23:40.455871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c860184a399'
down_revision: Union[str, None] = '3312a30ce7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_requests', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam_requests', 'classrooms', ['classroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_requests', type_='foreignkey')
    op.drop_column('exam_requests', 'classroom_id')
    # ### end Alembic commands ###
