"""Update professors table

Revision ID: 6f597b28cf4e
Revises: f05bfe385c42
Create Date: 2024-11-25 19:27:46.779546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f597b28cf4e'
down_revision: Union[str, None] = 'f05bfe385c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('professors', sa.Column('faculty_name', sa.String(), nullable=True))
    op.add_column('professors', sa.Column('department_name', sa.String(), nullable=True))
    op.alter_column('professors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('professors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_professors_first_name', table_name='professors')
    op.drop_index('ix_professors_last_name', table_name='professors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_professors_last_name', 'professors', ['last_name'], unique=False)
    op.create_index('ix_professors_first_name', 'professors', ['first_name'], unique=False)
    op.alter_column('professors', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('professors', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('professors', 'department_name')
    op.drop_column('professors', 'faculty_name')
    op.drop_column('professors', 'phone_number')
    # ### end Alembic commands ###
